on:
  push:
  pull_request:

name: build_singularity_5

jobs:
  build_singularity_5:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Build Singularity_5
        run: ./build_singularity_5.sh

      - name: Run container
        run: ./run_singularity_5.sh

